name: DotNet-RestAPI V2 Publish to Nuget

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: |
        echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV 
        echo "SANDBOX_USERNAME=${{ secrets.SANDBOX_USERNAME }}" >> $GITHUB_ENV
        echo "SANDBOX_PASSWORD=${{ secrets.SANDBOX_PASSWORD }}" >> $GITHUB_ENV
    - name: Print Version
      run: |
        echo $VERSION
        echo ${{ env.VERSION }}
    - name: Checkout
      uses: actions/checkout@v3     
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          2.x.x
          4.x.x
          2.2.x
          3.1.x
    - name: Restore Tests
      run: dotnet restore Avalara.AvaTax.RestClient.Test.csproj
      working-directory: tests
    - name: Build Tests
      run: dotnet build Avalara.AvaTax.RestClient.Test.csproj --no-restore --configuration Release
      working-directory: tests
    - name: Run Tests
      run: dotnet test Avalara.AvaTax.RestClient.Test.csproj --no-build --verbosity diag
      working-directory: tests
    - name: Create Assembly Signing Key
      run: echo $ASSEMBLY_SIGNING_KEY | base64 -d > Avalara.AvaTax.RestClient.snk
      working-directory: src
      env:
        ASSEMBLY_SIGNING_KEY: ${{ secrets.ASSEMBLY_SIGNING_KEY }}
    - name: Build Package
      run: dotnet build --no-restore --configuration Release
      working-directory: src
    - name: Pack Package
      run: dotnet pack Avalara.AvaTax.RestClient.csproj -p:NuspecFile=Avalara.AvaTax.RestClient.nuspec -o . --no-build
      working-directory: src
    - name: Publish Package
      run: dotnet nuget push Avalara.AvaTax.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN} 
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_TOKEN }}