name: DotNet- Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  #workflow_dispatch:
    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set env
      run: |
        echo "SANDBOX_USERNAME=${{ secrets.SANDBOX_USERNAME }}" >> $GITHUB_ENV
        echo "SANDBOX_PASSWORD=${{ secrets.SANDBOX_PASSWORD }}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Create Assembly Signing Key
      run: | 
        env
        echo $ASSEMBLY_SIGNING_KEY | base64 -d > src/Avalara.AvaTax.RestClient.snk
      env:
        ASSEMBLY_SIGNING_KEY: ${{ secrets.ASSEMBLY_SIGNING_KEY }}
    - name: Restore Tests
      run: dotnet restore Avalara.AvaTax.RestClient.Test.csproj
      working-directory: tests
    - name: Build Tests
      run: dotnet build Avalara.AvaTax.RestClient.Test.csproj --no-restore --configuration Release
      working-directory: tests
    - name: Run Tests
      run: dotnet test Avalara.AvaTax.RestClient.Test.csproj --no-build --verbosity diag
      working-directory: tests
